### PR TITLE
A skeleton for a benchmark suite.

### PR DESCRIPTION
**Pull request by bd82**

### CODE REVIEW

**Comment by bd82** [comment]
The input used was really tiny as I could not get this package to parse even smallish real files.
I believe more work is needed...

Anyhow this tiny benchmark shows about 2 **orders of magnitude** faster performance vs a pegjs implementation. even though the architecture is more complex (creates a CST) .

I also think that the more complex the input the greater the difference may become as there may be some exponential issue with pegjs handling of expressions...

I also believe the performance of the chevrotain based parser could be improved either by library optimizations (CST creation optimizations). and/or by following some of the suggestions here:
 http://sap.github.io/chevrotain/website/FAQ.html#PERFORMANCE

Additional investigations must wait for greater maturity of this package so a larger more meaningful sample may be used.

**Comment by bd82** [comment]
I will hopefully fix the linting issues tomorrow so this can be merged.

**Comment by thorbenvh8** [comment]
Yes I'm trying to include it with prettier now and all kinds of bugs popping up, which explains why your input was so tiny :)

**Comment by bd82** [comment]
> Yes I'm trying to include it with prettier now and all kinds of bugs popping up, which explains why your input was so tiny :)

Maybe a test suite that checks out and parses **several hundred thousands** lines of source code
of popular java repos is warranted.

**Comment by bd82** [comment]
Btw: upcoming changes in version 3.0 already include a **50% performance boost**
for the similar scenario of Parsing + CST building for a complex grammar.
* https://github.com/SAP/chevrotain/pull/665

It would be interesting how fast we can get this Parser to be 😄

**Comment by bd82** [comment]
the benchmark is included in the other open pull request with theupdate to 3.2.0

**Pull request closed without merging**
